const DBKEY="smart_scorebook_v2";
const seed={school:"English Smart Classroom",teacher:"ครูผู้สอน",classes:[{id:"M3-1",name:"ม.3/1",code:"ENG31"},{id:"M3-2",name:"ม.3/2",code:"ENG32"}],
students:[{id:1,name:"กิตติ",no:1,classId:"M3-1"},{id:2,name:"มินตรา",no:2,classId:"M3-1"},{id:3,name:"ภัทร",no:3,classId:"M3-1"},{id:4,name:"อัญญา",no:4,classId:"M3-2"}],
assessments:[{id:1,name:"Speaking Quiz",max:10,weight:1},{id:2,name:"Listening Quiz",max:10,weight:1},{id:3,name:"Worksheet",max:10,weight:1}],
scores:[],attendance:[],currentUser:null};
let db=JSON.parse(localStorage.getItem(DBKEY)||"null")||seed;
const save=()=>localStorage.setItem(DBKEY,JSON.stringify(db));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const cls=id=>db.classes.find(x=>x.id===id);
const pct=(a,b)=>b?Math.round(a/b*100):0;
function toast(t){let e=document.createElement("div");e.className="toast";e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2000)}
function home(){document.getElementById("app").innerHTML=`<div class="login"><div class="loginbox"><div class="logo" style="margin:auto">📚</div><h1>Smart Scorebook <span style="color:#6d5dfc">V2</span></h1><p class="muted">สมุดบันทึกคะแนน • เช็กชื่อ • วิเคราะห์ผล • ห้องเรียนออนไลน์</p><div class="roles"><div class="role"><div class="emoji">👩‍🏫</div><h3>Teacher Dashboard</h3><p>สร้างห้องเรียน จัดการนักเรียน เช็กชื่อ บันทึกคะแนน และวิเคราะห์ผล</p><button class="btn primary" onclick="teacher()">เข้าสู่ระบบครู</button></div><div class="role"><div class="emoji">🎧</div><h3>Student Mode</h3><p>เข้าห้องด้วยรหัสห้องและเลขที่ เพื่อตรวจสอบผลการเรียน</p><button class="btn" onclick="student()">เข้าห้องเรียน</button></div></div></div></div>`}
function shell(title,content,active){document.getElementById("app").innerHTML=`<div class="app"><aside class="side"><div class="brand"><div class="logo">📚</div><span>Smart V2</span></div><div class="nav">
<button class="${active==="dash"?"active":""}" onclick="teacher('dash')">🏠 <span>ภาพรวม</span></button>
<button class="${active==="att"?"active":""}" onclick="teacher('att')">✅ <span>เช็กชื่อ</span></button>
<button class="${active==="score"?"active":""}" onclick="teacher('score')">📊 <span>คะแนน</span></button>
<button class="${active==="stu"?"active":""}" onclick="teacher('stu')">👥 <span>นักเรียน</span></button>
<button class="${active==="class"?"active":""}" onclick="teacher('class')">🏫 <span>ห้องเรียน</span></button>
<button class="${active==="report"?"active":""}" onclick="teacher('report')">📈 <span>วิเคราะห์</span></button>
</div><div style="position:absolute;bottom:15px;left:15px;right:15px"><button class="nav" onclick="home()">← <span>หน้าหลัก</span></button></div></aside><main class="main"><div class="top"><div><h1>${title}</h1><div class="muted">${db.school} • ${db.teacher}</div></div><button class="btn gray" onclick="exportCSV()">⬇ Export</button></div>${content}</main></div>`}
function teacher(page="dash"){if(page==="dash")dash();else if(page==="att")att();else if(page==="score")score();else if(page==="stu")students();else if(page==="class")classes();else report()}
function dash(){let n=db.students.length,a=db.attendance.filter(x=>x.date===today()),p=a.filter(x=>x.status==="present").length,ss=db.scores,t=ss.reduce((x,y)=>x+y.score,0),m=ss.reduce((x,y)=>x+(db.assessments.find(z=>z.id===y.assessmentId)?.max||0),0);shell("Teacher Dashboard",`
<div class="grid"><div class="card stat"><div class="label">นักเรียน</div><div class="num">${n}</div><div class="kpi">${db.classes.length} ห้องเรียน</div></div><div class="card stat"><div class="label">มาเรียนวันนี้</div><div class="num">${p}/${n}</div><div class="kpi">${today()}</div></div><div class="card stat"><div class="label">คะแนนเฉลี่ยรวม</div><div class="num">${pct(t,m)}%</div><div class="kpi">${ss.length} รายการ</div></div><div class="card stat"><div class="label">กิจกรรม</div><div class="num">${db.assessments.length}</div><div class="kpi">ประเมินผล</div></div></div>
<div class="section hero"><h2>⚡ Smart Classroom Control Center</h2><p>ระบบพร้อมสำหรับเช็กชื่อและบันทึกคะแนนของวันนี้</p><div class="toolbar" style="margin-top:16px"><button class="btn" onclick="att()">✅ เช็กชื่อวันนี้</button><button class="btn" onclick="score()">📝 บันทึกคะแนน</button><button class="btn" onclick="newStudent()">👤 เพิ่มนักเรียน</button><button class="btn" onclick="newClass()">🏫 สร้างห้องเรียน</button></div></div>
<div class="section card"><div class="section-head"><h2>👥 นักเรียนล่าสุด</h2><button class="btn gray" onclick="students()">ดูทั้งหมด</button></div>${studentTable(db.students.slice(0,8))}</div>`,"dash")}
function studentTable(ss){if(!ss.length)return`<div class="empty">ยังไม่มีข้อมูล</div>`;return`<div class="table-wrap"><table class="table"><tr><th>เลขที่</th><th>ชื่อ</th><th>ห้อง</th><th>คะแนน</th><th>Progress</th></tr>${ss.map(s=>{let z=db.scores.filter(x=>x.studentId===s.id),t=z.reduce((a,b)=>a+b.score,0),m=z.reduce((a,b)=>a+(db.assessments.find(q=>q.id===b.assessmentId)?.max||0),0),q=pct(t,m);return`<tr><td>${s.no}</td><td><b>${esc(s.name)}</b></td><td>${cls(s.classId)?.name||"-"}</td><td>${t}/${m}</td><td><div class="progress"><span style="width:${q}%"></span></div></td></tr>`}).join("")}</table></div>`}
function att(){shell("เช็กชื่อเข้าเรียน",`<div class="card"><div class="toolbar"><input class="input" id="date" type="date" value="${today()}" onchange="loadAtt()"><select class="input" id="ac" onchange="loadAtt()"><option value="">ทุกห้อง</option>${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select><button class="btn primary" onclick="saveAtt()">💾 บันทึก</button><button class="btn green" onclick="markAll('present')">✓ มาครบ</button></div></div><div class="section card" id="attBox"></div>`,"att");loadAtt()}
function loadAtt(){let d=document.getElementById("date").value,c=document.getElementById("ac").value,ss=db.students.filter(s=>!c||s.classId===c);document.getElementById("attBox").innerHTML=`<div class="section-head"><h2>เช็กชื่อ ${d}</h2><span class="muted">${ss.length} คน</span></div><div class="table-wrap"><table class="table"><tr><th>เลขที่</th><th>นักเรียน</th><th>สถานะ</th></tr>${ss.map(s=>{let a=db.attendance.find(x=>x.studentId===s.id&&x.date===d),st=a?.status||"present";return`<tr><td>${s.no}</td><td>${esc(s.name)}</td><td><select class="input ast" data-id="${s.id}"><option value="present" ${st==="present"?"selected":""}>มาเรียน</option><option value="late" ${st==="late"?"selected":""}>สาย</option><option value="leave" ${st==="leave"?"selected":""}>ลา</option><option value="absent" ${st==="absent"?"selected":""}>ขาด</option></select></td></tr>`}).join("")}</table></div>`}
function markAll(v){document.querySelectorAll(".ast").forEach(e=>e.value=v)}
function saveAtt(){let d=document.getElementById("date").value;document.querySelectorAll(".ast").forEach(e=>{let id=+e.dataset.id,i=db.attendance.findIndex(x=>x.studentId===id&&x.date===d),r={studentId:id,date:d,status:e.value};i>=0?db.attendance[i]=r:db.attendance.push(r)});save();toast("บันทึกการเช็กชื่อแล้ว")}
function score(){shell("สมุดบันทึกคะแนน",`<div class="card"><div class="toolbar"><select class="input" id="sc" onchange="loadScore()"><option value="">ทุกห้อง</option>${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select><select class="input" id="ass" onchange="loadScore()">${db.assessments.map(a=>`<option value="${a.id}">${esc(a.name)} / ${a.max}</option>`).join("")}</select><button class="btn" onclick="newAssessment()">＋ เพิ่มกิจกรรม</button><button class="btn primary" onclick="saveScore()">💾 บันทึกคะแนน</button></div></div><div class="section card" id="scoreBox"></div>`,"score");loadScore()}
function loadScore(){let c=document.getElementById("sc").value,a=+document.getElementById("ass").value,as=db.assessments.find(x=>x.id===a),ss=db.students.filter(s=>!c||s.classId===c);document.getElementById("scoreBox").innerHTML=`<div class="section-head"><h2>${esc(as?.name||"")}</h2><span class="muted">เต็ม ${as?.max||0}</span></div><div class="table-wrap"><table class="table"><tr><th>เลขที่</th><th>นักเรียน</th><th>ห้อง</th><th>คะแนน</th></tr>${ss.map(s=>{let z=db.scores.find(x=>x.studentId===s.id&&x.assessmentId===a);return`<tr><td>${s.no}</td><td>${esc(s.name)}</td><td>${cls(s.classId)?.name}</td><td><input class="input si" data-id="${s.id}" type="number" min="0" max="${as?.max}" value="${z?.score??""}" style="width:100px"></td></tr>`}).join("")}</table></div>`}
function saveScore(){let a=+document.getElementById("ass").value,as=db.assessments.find(x=>x.id===a);document.querySelectorAll(".si").forEach(e=>{if(e.value==="")return;let id=+e.dataset.id,i=db.scores.findIndex(x=>x.studentId===id&&x.assessmentId===a),r={studentId:id,assessmentId:a,score:Math.min(as.max,Math.max(0,+e.value))};i>=0?db.scores[i]=r:db.scores.push(r)});save();toast("บันทึกคะแนนแล้ว")}
function students(){shell("จัดการนักเรียน",`<div class="card"><div class="toolbar"><input class="input" id="sq" placeholder="🔎 ค้นหานักเรียน" oninput="loadStu()"><select class="input" id="scl" onchange="loadStu()"><option value="">ทุกห้อง</option>${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select><button class="btn primary" onclick="newStudent()">＋ เพิ่มนักเรียน</button></div></div><div class="section card" id="stuBox"></div>`,"stu");loadStu()}
function loadStu(){let q=(document.getElementById("sq")?.value||"").toLowerCase(),c=document.getElementById("scl")?.value,ss=db.students.filter(s=>(!q||s.name.toLowerCase().includes(q))&&(!c||s.classId===c));document.getElementById("stuBox").innerHTML=studentTable(ss)}
function classes(){shell("ห้องเรียน",`<div class="card"><div class="section-head"><h2>Class Management</h2><button class="btn primary" onclick="newClass()">＋ สร้างห้อง</button></div><div class="table-wrap"><table class="table"><tr><th>ห้อง</th><th>Class Code</th><th>นักเรียน</th><th>การจัดการ</th></tr>${db.classes.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td><span class="pill leave">${esc(c.code)}</span></td><td>${db.students.filter(s=>s.classId===c.id).length}</td><td><button class="btn gray" onclick="copyText('${c.code}')">คัดลอกรหัส</button></td></tr>`).join("")}</table></div></div>`,"class")}
function report(){let rows=db.students.map(s=>{let z=db.scores.filter(x=>x.studentId===s.id),t=z.reduce((a,b)=>a+b.score,0),m=z.reduce((a,b)=>a+(db.assessments.find(q=>q.id===b.assessmentId)?.max||0),0),a=db.attendance.filter(x=>x.studentId===s.id),p=a.filter(x=>x.status==="present").length;return{s,t,m,a,p}});shell("วิเคราะห์ผลการเรียน",`<div class="grid"><div class="card stat"><div class="label">นักเรียนต้องติดตาม</div><div class="num">${rows.filter(r=>r.m&&r.t/r.m<.5).length}</div></div><div class="card stat"><div class="label">คะแนนเฉลี่ย</div><div class="num">${pct(rows.reduce((a,r)=>a+r.t,0),rows.reduce((a,r)=>a+r.m,0))}%</div></div><div class="card stat"><div class="label">อัตรามาเรียน</div><div class="num">${pct(rows.reduce((a,r)=>a+r.p,0),rows.reduce((a,r)=>a+r.a.length,0))}%</div></div><div class="card stat"><div class="label">ห้องเรียน</div><div class="num">${db.classes.length}</div></div></div><div class="section card"><div class="section-head"><h2>Student Insight</h2><span class="muted">ระบบจัดกลุ่มจากข้อมูลคะแนนและการเข้าเรียน</span></div><div class="table-wrap"><table class="table"><tr><th>นักเรียน</th><th>คะแนน</th><th>มาเรียน</th><th>Insight</th></tr>${rows.map(r=>{let q=pct(r.t,r.m),ap=pct(r.p,r.a.length);let tag=q<50?"ควรติดตามด้านคะแนน":ap<80?"ควรติดตามการเข้าเรียน":"ปกติ";let cc=tag==="ปกติ"?"p":"a";return`<tr><td>${esc(r.s.name)}</td><td>${q}%</td><td>${ap}%</td><td><span class="pill ${cc}">${tag}</span></td></tr>`}).join("")}</table></div></div>`,"report")}
function modal(title,body,ok,fn){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><div class="section-head"><h2>${title}</h2><button class="btn gray" onclick="closeModal()">×</button></div>${body}<div class="toolbar" style="justify-content:flex-end;margin-top:18px"><button class="btn gray" onclick="closeModal()">ยกเลิก</button><button class="btn primary" id="mok">${ok}</button></div></div></div>`);document.getElementById("mok").onclick=fn}
function closeModal(){document.getElementById("modal")?.remove()}
function newStudent(){modal("เพิ่มนักเรียน",`<div class="form"><input class="input" id="mn" placeholder="ชื่อ-นามสกุล"><input class="input" id="mno" type="number" placeholder="เลขที่"><select class="input full" id="mc">${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select></div>`,"เพิ่ม",()=>{db.students.push({id:Date.now(),name:document.getElementById("mn").value.trim(),no:+document.getElementById("mno").value,classId:document.getElementById("mc").value});save();closeModal();students()})}
function newClass(){modal("สร้างห้องเรียน",`<div class="form"><input class="input" id="cn" placeholder="ชื่อห้อง เช่น ม.3/3"><input class="input" id="cc" placeholder="รหัสเข้าห้อง เช่น ENG33"></div>`,"สร้าง",()=>{db.classes.push({id:"C"+Date.now(),name:document.getElementById("cn").value.trim(),code:document.getElementById("cc").value.trim().toUpperCase()});save();closeModal();classes()})}
function newAssessment(){modal("เพิ่มกิจกรรม",`<div class="form"><input class="input full" id="an" placeholder="ชื่อกิจกรรม เช่น Speaking Task"><input class="input" id="am" type="number" min="1" placeholder="คะแนนเต็ม"><input class="input" id="aw" type="number" min="1" value="1" placeholder="น้ำหนัก"></div>`,"เพิ่ม",()=>{db.assessments.push({id:Date.now(),name:document.getElementById("an").value,max:+document.getElementById("am").value,weight:+document.getElementById("aw").value});save();closeModal();score()})}
function student(){document.getElementById("app").innerHTML=`<div class="login"><div class="loginbox"><div class="logo" style="margin:auto">🎧</div><h1>Student Mode</h1><p class="muted">กรอกรหัสห้องเรียนและเลขที่</p><div class="toolbar" style="justify-content:center"><input class="input" id="joinCode" placeholder="Class Code"><input class="input" id="joinNo" type="number" placeholder="เลขที่"></div><button class="btn primary" style="margin-top:12px" onclick="join()">เข้าห้องเรียน</button><div style="margin-top:15px"><button class="btn gray" onclick="home()">← กลับหน้าหลัก</button></div></div></div>`}
function join(){let code=document.getElementById("joinCode").value.trim().toUpperCase(),no=+document.getElementById("joinNo").value,c=db.classes.find(x=>x.code===code),s=db.students.find(x=>x.classId===c?.id&&x.no===no);if(!s){toast("ไม่พบข้อมูล กรุณาตรวจสอบรหัสห้องและเลขที่");return}studentDashboard(s)}
function studentDashboard(s){let z=db.scores.filter(x=>x.studentId===s.id),t=z.reduce((a,b)=>a+b.score,0),m=z.reduce((a,b)=>a+(db.assessments.find(q=>q.id===b.assessmentId)?.max||0),0),a=db.attendance.filter(x=>x.studentId===s.id),p=a.filter(x=>x.status==="present").length;document.getElementById("app").innerHTML=`<div class="main" style="margin-left:0;width:100%;max-width:1000px;margin:auto"><div class="top"><div><h1>🎧 ${esc(s.name)}</h1><div class="muted">${cls(s.classId)?.name} • เลขที่ ${s.no}</div></div><button class="btn gray" onclick="student()">← ออกจากห้อง</button></div><div class="hero"><h2>My Learning Dashboard</h2><p>ดูความก้าวหน้าของคุณได้ทันที</p></div><div class="section mini-grid"><div class="card stat"><div class="label">คะแนนรวม</div><div class="num">${t}/${m}</div></div><div class="card stat"><div class="label">ผลสัมฤทธิ์</div><div class="num">${pct(t,m)}%</div></div><div class="card stat"><div class="label">การมาเรียน</div><div class="num">${pct(p,a.length)}%</div></div></div><div class="section card"><div class="section-head"><h2>📊 My Scores</h2></div><table class="table">${z.map(x=>`<tr><td>${esc(db.assessments.find(q=>q.id===x.assessmentId)?.name||"")}</td><td>${x.score}/${db.assessments.find(q=>q.id===x.assessmentId)?.max}</td></tr>`).join("")||"<tr><td>ยังไม่มีคะแนน</td></tr>"}</table></div></div>`}
function copyText(t){navigator.clipboard?.writeText(t);toast("คัดลอกรหัสแล้ว")}
function exportCSV(){let out=["No,Name,Class,Score,Max,Percent,Present,Attendance"];db.students.forEach(s=>{let z=db.scores.filter(x=>x.studentId===s.id),t=z.reduce((a,b)=>a+b.score,0),m=z.reduce((a,b)=>a+(db.assessments.find(q=>q.id===b.assessmentId)?.max||0),0),a=db.attendance.filter(x=>x.studentId===s.id),p=a.filter(x=>x.status==="present").length;out.push([s.no,`"${s.name}"`,cls(s.classId)?.name,t,m,pct(t,m),p,a.length].join(","))});let b=new Blob(["\ufeff"+out.join("\\n")],{type:"text/csv"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="smart-scorebook-v2.csv";a.click();URL.revokeObjectURL(u)}
home();